stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Admission_Prediction.csv
    outs:
    - data/raw/Admission_Prediction.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/Admission_Prediction.csv
    outs:
      - data/processed/train_Admission_Prediction.csv
      - data/processed/test_Admission_Prediction.csv