stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Admission_Prediction.csv
    outs:
    - data/raw/Admission_Prediction.csv

  process_data:
    cmd: python src/pre_process_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/pre_process_data.py
      - data/raw/Admission_Prediction.csv
    outs:
      - data/preprocessing/Admission_Prediction.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/preprocessing/Admission_Prediction.csv
    outs:
      - data/processed/train_Admission_Prediction.csv
      - data/processed/test_Admission_Prediction.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_Admission_Prediction.csv
      - data/processed/test_Admission_Prediction.csv
      - src/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    #metrics:
    #  - report/scores.json:
    #      cache: false
    #  - report/params.json:
    #      cache: false
    #outs:
    #  - saved_models/model.joblib

    #log_production_model:
    #  cmd: python src/log_production_model.py --config=params.yaml
    #  deps:
    #  - src/log_production_model.py
