base:
  project: Admission-Prediction
  random_state: 42
  target_col: 'Chance_of_Admit'

data_source:
  s3_source: data_given/Admission_Prediction.csv

load_data:
  raw_dataset_csv: data/raw/Admission_Prediction.csv

preprocessing_data:
  process_dataset_csv: data/preprocessing/Admission_Prediction.csv
  drop_col: 'Serial_No.'

split_data:
  train_path: data/processed/train_Admission_Prediction.csv
  test_path: data/processed/test_Admission_Prediction.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4
      #alpha: 0.88
      #l1_ratio: 0.89
      #alpha: 0.5
      #l1_ratio: 0.5

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetAdmissionModel
  remote_server_uri: http://localhost:1234/
